# Deploy branch is followed by Posit Connect
name: Update Requirements on Deploy Branch

on:
  push:
    branches:
      - main  # Trigger when pushing to main

jobs:
  ci:
    env:
      UV_SYSTEM_PYTHON: true
      CONNECT_SERVER:  ${{ secrets.CONNECT_SERVER }}
      CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Generate requirements.txt with `uv`
        run: uv export --no-hashes -o requirements.txt

      - name: Generate rsconnect-python manifest.json
        run: uvx --from rsconnect-python rsconnect write-manifest shiny . --entrypoint pyshinywikidata.app:app

      - name: Commit changes and push to deploy branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt manifest.json
          git commit -m "Update requirements on new commit from main" || echo "No changes to commit"
          git push origin --force HEAD:deploy  # Push to deploy branch, using force because of diverging branches

      - name: Checkout deploy
        uses: actions/checkout@v4
        with:
          ref: deploy
      
      - name: Deploy the deploy branch to Connect
        run: uvx --from rsconnect-python rsconnect deploy --server=$CONNECT_SERVER --api-key=$CONNECT_API_KEY manifest manifest.json
